### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device when initializing CUDA for gsplat

### ISSUE THREAD

**Issue by ChaosAdmStudent** [nerfstudio-project/gsplat#302]
I am working with the following:

Ubuntu 22.04.4 LTS
Nvidia driver: 555.42.06
Nvidia RTX 3080 Ti

I have multiple cuda installations in the /usr/local folder but I have added the cuda-12.1 bin to PATH and lib64 to LD_LIBRARY_PATH

I have installed the CUDA12.1 pytorch binaries using pip, which based on my online research shows that it ships with the CUDA binaries to run it without external setup.

However, if I don’t add the /usr/local/cuda-12.1/bin to the PATH and try to run the project it throws a “gsplat: No CUDA toolkit found. gsplat will be disabled”. I am assuming this is because this repository has custom CUDA kernels which are not just pure pytorch code.

After adding to PATH, I dont get this error anymore, it starts initializing but fails after a while saying “RuntimeError: CUDA error: no kernel image is available for execution on the device”

Looking at the driver compatibility, it seems that the nvidia driver version 555.42.02+ is not compatible with any other CUDA except 12.5. Is this the reason the code is not running? Do I need a different nvidia driver? 

Perhaps this is why I can do basic CUDA device hosted operations in pure pytorch but it fails when trying to run this repository. Any tips would be heavily appreciated as this is all new to me.

**Comment by ChaosAdmStudent** [comment]
After some tinkering, I figured going with the gsplat installation that compiled gsplat during installation instead of JIT ended up fixing it for me. I wonder why that happened for knowledge sake though!

**Comment by kstoneriv3** [comment]
I encountered the same error with A30 GPU with Cuda 11.8. In my case, just compiling during the installation did not solve the issue but I was able to fix it by explicitly setting the compute capability of a GPU to target by modifying the `setup.py` as follows.

```python
    nvcc_flags += ["-gencode=arch=compute_80,code=sm_80", "-gencode=arch=compute_80,code=sm_80"]
```

So I assume that this error has something to do with targeting the proper compute capability when compiling.

**Comment by tianyufang1958** [comment]
The issue is fused-ssim was built with gpus with different computer power. The easiest solution for me is git clone https://github.com/rahul-goel/fused-ssim.git
Then pip install it.
