### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by HlKun** [nerfstudio-project/gsplat#741]
I successfully ran simple_trainer.py on a computer with an RTX 4090D GPU, CUDA 11.8, and PyTorch 2.4.0; then packaged it using PyInstaller. When running the packaged program on a computer with an RTX 3050 Ti GPU, I encountered the following error.

![Image](https://github.com/user-attachments/assets/4db6d176-fb43-4340-8b83-01b0d281f862)

It happens on this code!

![Image](https://github.com/user-attachments/assets/5da3a90e-7560-4565-a569-85dc7b48f6d0)

 However, this program could run normally on a computer equipped with an RTX 4060 GPU.

**Comment by HlKun** [comment]
The issue has been resolved. This was because "fused-ssim" was only compiled for the compute capability (CUDA architecture) of the current GPU during the build process. To ensure compatibility with other GPUs, it was necessary to modify nvcc_args to include additional compute architectures.

![Image](https://github.com/user-attachments/assets/05efa558-c70f-4725-b163-27f7de478eee)
